# Generated by Django 3.2 on 2021-05-06 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timeslot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_start', models.DateTimeField()),
                ('preferred_end', models.DateTimeField()),
            ],
        ),
    ]
