# Generated by Django 3.2 on 2021-05-07 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trolley', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='preferred_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='preferred_start',
            field=models.DateField(),
        ),
    ]
