# Generated by Django 3.2 on 2021-05-07 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trolley', '0003_auto_20210507_0206'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Timeslot',
        ),
    ]
