# Generated by Django 3.2 on 2021-04-25 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_alter_client_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='viewrequest',
            name='subject_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
