# Generated by Django 3.2 on 2021-04-25 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_auto_20210425_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewrequest',
            name='preferred_startdate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='viewrequest',
            name='subject_message',
            field=models.TextField(blank=True, default=None),
            preserve_default=False,
        ),
    ]
