# Generated by Django 3.2 on 2021-04-25 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_auto_20210425_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewrequest',
            name='preferred_startdate',
            field=models.DateField(blank=True),
        ),
    ]
