# Generated by Django 3.2 on 2021-04-27 02:23

from django.db import migrations, models
import tenants.models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_auto_20210426_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewrequest',
            name='viewing_date',
            field=models.DateField(validators=[tenants.models.valiDate]),
        ),
    ]
