# Generated by Django 3.2 on 2021-04-27 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0009_alter_viewrequest_viewing_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='requests',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.viewrequest'),
        ),
    ]
