# Generated by Django 3.2 on 2021-04-27 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0010_client_requests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='requests',
        ),
    ]
