# Generated by Django 3.2 on 2021-04-28 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0013_alter_client_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewrequest',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tenants.client'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=320, unique=True),
        ),
    ]
