# Generated by Django 3.2 on 2021-04-28 05:18

import django.core.validators
from django.db import migrations, models
import tenants.models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0014_auto_20210428_0231'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=320, unique=True)),
                ('phone', models.CharField(max_length=8)),
                ('viewing_date', models.DateField(validators=[tenants.models.valiDate])),
                ('viewing_time', models.TimeField(validators=[tenants.models.valiTime])),
                ('company_name', models.CharField(max_length=320)),
                ('company_size', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('space_needed', models.CharField(max_length=320)),
                ('preferred_startdate', models.DateField(blank=True, null=True)),
                ('subject_message', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='viewrequest',
            name='client',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='ViewRequest',
        ),
    ]
