# Generated by Django 3.2 on 2021-04-29 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0015_auto_20210428_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientrequest',
            name='email',
            field=models.EmailField(max_length=320),
        ),
    ]
