# Generated by Django 3.2 on 2021-04-30 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0016_alter_clientrequest_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientrequest',
            name='remarks',
            field=models.TextField(blank=True),
        ),
    ]
