# Generated by Django 3.2 on 2021-05-01 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0018_auto_20210501_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientrequest',
            name='remarks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.cradmin'),
        ),
    ]
