# Generated by Django 3.2 on 2021-05-02 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0019_clientrequest_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='cradmin',
            name='crequest',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tenants.clientrequest'),
            preserve_default=False,
        ),
    ]
