# Generated by Django 3.2 on 2021-05-02 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0020_cradmin_crequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientrequest',
            name='remarks',
        ),
    ]
