# Generated by Django 3.2 on 2021-05-02 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0022_clientrequest_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientrequest',
            name='remarks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.cradmin'),
        ),
    ]
