# Generated by Django 3.2 on 2021-05-02 09:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import tenants.models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0031_auto_20210502_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientrequest',
            name='phone',
            field=models.CharField(max_length=8, validators=[tenants.models.valiPhone]),
        ),
        migrations.AlterField(
            model_name='cradmin',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 2, 17, 35, 56, 21692, tzinfo=utc)),
        ),
    ]
