# Generated by Django 3.2 on 2021-05-02 09:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0032_auto_20210502_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cradmin',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 2, 17, 41, 39, 202112, tzinfo=utc)),
        ),
    ]
