# Generated by Django 3.2.2 on 2021-05-15 15:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0077_auto_20210515_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cradmin',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 15, 23, 28, 54, 742895)),
        ),
    ]
