# Generated by Django 3.2 on 2021-04-19 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='space',
            old_name='desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='space',
            old_name='seats',
            new_name='seat_capacity',
        ),
        migrations.RenameField(
            model_name='space',
            old_name='nametype',
            new_name='space_type',
        ),
    ]
