# Generated by Django 3.2 on 2021-04-19 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0006_validity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='validity',
            old_name='end_date',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='validity',
            old_name='end_time',
            new_name='start',
        ),
        migrations.RemoveField(
            model_name='validity',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='validity',
            name='start_time',
        ),
    ]
