# Generated by Django 3.2 on 2021-04-19 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0008_auto_20210419_1131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='space',
            old_name='mth_meetroom_credits',
            new_name='monthly_meeting_room_credits',
        ),
        migrations.RenameField(
            model_name='space',
            old_name='mth_print_credits',
            new_name='monthly_print_credits',
        ),
    ]
