# Generated by Django 3.2 on 2021-04-19 12:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0009_auto_20210419_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='monthly_print_credits',
            field=models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60)]),
        ),
    ]
