# Generated by Django 3.2 on 2021-04-20 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0012_auto_20210420_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='price',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='spaces.price'),
            preserve_default=False,
        ),
    ]
