# Generated by Django 3.2 on 2021-04-20 15:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0014_auto_20210420_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='cost',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6000)]),
        ),
        migrations.AlterField(
            model_name='price',
            name='min_count',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='price',
            name='unit_type',
            field=models.CharField(choices=[('hour', 'per hour'), ('day', 'per day'), ('month', 'per month')], max_length=30),
        ),
    ]
