# Generated by Django 3.2 on 2021-04-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0015_auto_20210420_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='valid_period',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
