# Generated by Django 3.2 on 2021-04-21 03:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0017_delete_validity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='monthly_print_credit_page',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60)]),
        ),
    ]
