# Generated by Django 3.2 on 2021-04-22 14:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0018_alter_space_monthly_print_credit_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='cost',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6000)]),
        ),
        migrations.AlterField(
            model_name='space',
            name='monthly_meeting_room_credit_hour',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='space',
            name='monthly_print_credit_page',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='space',
            name='seat_capacity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(40)]),
        ),
    ]
