# Generated by Django 3.2 on 2021-04-23 02:22

from django.db import migrations, models
import django.db.models.deletion
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0019_auto_20210422_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='photo',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
        migrations.AlterField(
            model_name='space',
            name='price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='spaces.price'),
        ),
    ]
