# Generated by Django 3.2 on 2021-04-23 02:53

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0020_auto_20210423_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='photo',
            field=pyuploadcare.dj.models.ImageField(),
        ),
    ]
