# Generated by Django 3.2 on 2021-05-01 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0025_auto_20210430_0341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='price',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='spaces.price'),
            preserve_default=False,
        ),
    ]
