# Generated by Django 3.2 on 2021-05-02 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0028_alter_price_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=6),
        ),
    ]
