# Generated by Django 3.2 on 2021-05-02 15:13

import django.core.validators
from django.db import migrations, models
import spaces.models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0029_alter_price_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=6, validators=[spaces.models.clean_cost]),
        ),
        migrations.AlterField(
            model_name='price',
            name='min_count',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100), spaces.models.clean_count]),
        ),
    ]
